"""Deterministic, source-aligned semantic captions for Spatial-CoT.

The renderer caption intentionally describes *what* is audible and leaves
where/when/how-loud controls to ScenePlan.  Surface diversity is generated by
an explicit Cartesian template catalog rather than random paraphrasing.  Every
render also records exact source and transcript character spans so token-level
regional conditioning never has to recover source binding with a regex.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from typing import Any, Iterable, Mapping, Sequence


SEMANTIC_CAPTION_TEMPLATE_VERSION = "spatial_source_regions_v3"


# All frames accept a neutral noun phrase and make no temporal, spatial, room,
# prominence, or source-count claims.  Keeping these facts out of free text
# preserves ScenePlan as the sole control authority.
_SCENE_FRAMES: tuple[tuple[str, str], ...] = (
    ("This spatial audio scene contains ", ""),
    ("This FOA recording presents ", ""),
    ("The sound field carries ", ""),
    ("This multichannel scene brings together ", ""),
    ("The recording features ", ""),
    ("This spatial soundscape includes ", ""),
    ("The scene renders ", ""),
    ("This spatial recording captures ", ""),
    ("The FOA sound field contains ", ""),
    ("This scene presents ", ""),
    ("This spatial mixture brings together ", ""),
    ("The recording carries ", ""),
    ("This soundscape features ", ""),
    ("The spatial field renders ", ""),
    ("This spatial capture includes ", ""),
    ("This multichannel recording presents ", ""),
)


# body prefix, middle separator, final separator.  The prefix remains visible
# for a single-source caption, so all catalog axes contribute real diversity.
_BODY_STYLES: tuple[tuple[str, str, str], ...] = (
    ("", "; ", "; and "),
    ("the following audible sources: ", "; ", "; and "),
    ("source material consisting of ", "; ", "; together with "),
    ("an arrangement of ", "; ", "; alongside "),
    ("audible content comprising ", "; ", "; plus "),
    ("the following source set: ", "; ", "; as well as "),
    ("a selection of ", "; ", "; accompanied by "),
    ("a collection of ", "; ", "; together with "),
)


# Several styles expose the exact persistent ID in natural or compact notation.
# The machine-readable semantic span covers only ``{content}``: persistent ID
# is represented by its independent regional slot embedding, while wrapper
# words and punctuation must not dilute the content summary pooled for that
# slot. All forms remain grammatical for short labels and long captions.
_SOURCE_WRAPPERS: tuple[str, ...] = (
    "{content}",
    "{source_id}: {content}",
    "{source_id} — {content}",
    "[{source_id}] {content}",
    "{content} ({source_id})",
    "the {source_id} content: {content}",
    "the description for {source_id}: {content}",
    "the audible material for {source_id}: {content}",
)


_CLOSINGS: tuple[str, ...] = (
    ".",
    "; these elements share one spatial sound field.",
)


SEMANTIC_CAPTION_TEMPLATE_COUNT = (
    len(_SCENE_FRAMES)
    * len(_BODY_STYLES)
    * len(_SOURCE_WRAPPERS)
    * len(_CLOSINGS)
)

if SEMANTIC_CAPTION_TEMPLATE_COUNT != 2048:  # fail closed on catalog drift
    raise RuntimeError(
        "Spatial-CoT semantic caption catalog must contain exactly 2048 "
        f"templates, got {SEMANTIC_CAPTION_TEMPLATE_COUNT}"
    )


@dataclass(frozen=True)
class CaptionCharacterRegion:
    """One half-open character region in a rendered semantic caption."""

    source_id: str
    source_slot: int
    start: int
    end: int
    role: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "source_slot": self.source_slot,
            "start": self.start,
            "end": self.end,
            "role": self.role,
        }


@dataclass(frozen=True)
class SemanticCaptionRender:
    """Caption text plus deterministic template and source-region metadata."""

    text: str
    template_id: int
    source_regions: tuple[CaptionCharacterRegion, ...]
    transcript_regions: tuple[CaptionCharacterRegion, ...]

    def metadata(self) -> dict[str, Any]:
        return {
            "version": SEMANTIC_CAPTION_TEMPLATE_VERSION,
            "template_id": self.template_id,
            "template_count": SEMANTIC_CAPTION_TEMPLATE_COUNT,
            "source_regions": [region.as_dict() for region in self.source_regions],
            "transcript_regions": [
                region.as_dict() for region in self.transcript_regions
            ],
        }


@dataclass(frozen=True)
class _SourcePhrase:
    source_id: str
    source_slot: int
    text: str
    transcript_start: int | None
    transcript_end: int | None


def _stable_payload(value: Any) -> str:
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    except TypeError:
        return str(value)


def choose_semantic_caption_template(
    template_key: Any,
    *,
    sources: Sequence[Mapping[str, Any]] = (),
) -> int:
    """Map a stable family key to one of the 2,048 surface templates."""

    if template_key is None:
        template_key = [
            {
                "source_id": source.get("source_id"),
                "source_uid": source.get("source_uid"),
                "event": source.get("event"),
                "transcript": (source.get("content") or {}).get("transcript"),
            }
            for source in sources
        ]
    digest = hashlib.blake2b(
        _stable_payload(template_key).encode("utf-8"), digest_size=8
    ).digest()
    return int.from_bytes(digest, "big") % SEMANTIC_CAPTION_TEMPLATE_COUNT


def _decode_template_id(template_id: int) -> tuple[int, int, int, int]:
    if isinstance(template_id, bool) or not isinstance(template_id, int):
        raise TypeError("semantic caption template_id must be an integer")
    if not 0 <= template_id < SEMANTIC_CAPTION_TEMPLATE_COUNT:
        raise ValueError(
            "semantic caption template_id must be in "
            f"[0, {SEMANTIC_CAPTION_TEMPLATE_COUNT}), got {template_id}"
        )
    value = template_id
    frame_index, value = value % len(_SCENE_FRAMES), value // len(_SCENE_FRAMES)
    body_index, value = value % len(_BODY_STYLES), value // len(_BODY_STYLES)
    wrapper_index, value = (
        value % len(_SOURCE_WRAPPERS),
        value // len(_SOURCE_WRAPPERS),
    )
    closing_index = value % len(_CLOSINGS)
    return frame_index, body_index, wrapper_index, closing_index


def _source_phrases(sources: Sequence[Mapping[str, Any]]) -> list[_SourcePhrase]:
    phrases: list[_SourcePhrase] = []
    seen_source_ids: set[str] = set()
    seen_source_slots: set[int] = set()
    for source_index, source in enumerate(sources):
        source_id = str(source.get("source_id") or f"source_{source_index}")
        if source_id in seen_source_ids:
            raise ValueError(f"duplicate semantic-caption source_id: {source_id!r}")
        seen_source_ids.add(source_id)
        source_slot = source_index
        if source_id.startswith("source_") and source_id[7:].isdigit():
            source_slot = int(source_id[7:])
        elif source_id.startswith("s") and source_id[1:].isdigit():
            source_slot = int(source_id[1:])
        if source_slot < 0 or source_slot in seen_source_slots:
            raise ValueError(
                f"invalid/duplicate semantic-caption source slot: {source_slot}"
            )
        seen_source_slots.add(source_slot)

        event = source.get("event") or {}
        label = " ".join(
            str(event.get("label") or event.get("category") or "audio event").split()
        ).rstrip(" .!?;:") or "audio event"
        transcript = str((source.get("content") or {}).get("transcript") or "").strip()
        transcript_start: int | None = None
        transcript_end: int | None = None
        if transcript:
            quoted = json.dumps(transcript, ensure_ascii=False)
            if label.casefold() == "speech":
                prefix = "speech saying "
            else:
                prefix = f"{label}; spoken words: "
            text = prefix + quoted
            # Region excludes JSON quote characters but includes escaped content.
            transcript_start = len(prefix) + 1
            transcript_end = len(text) - 1
        else:
            text = label
        phrases.append(
            _SourcePhrase(
                source_id=source_id,
                source_slot=source_slot,
                text=text,
                transcript_start=transcript_start,
                transcript_end=transcript_end,
            )
        )
    return phrases


def render_semantic_caption(
    sources: Iterable[Mapping[str, Any]],
    *,
    template_key: Any = None,
    template_id: int | None = None,
) -> SemanticCaptionRender:
    """Render a diverse caption while preserving exact source boundaries.

    ``template_key`` should be conversation-stable (normally ``family_id``), so
    spatial/gain/timing edits retain the same wording.  ``template_id`` is an
    explicit audit override and is mutually exclusive with ``template_key``.
    """

    source_list = list(sources)
    if template_id is not None and template_key is not None:
        raise ValueError("provide semantic caption template_key or template_id, not both")
    if template_id is None:
        template_id = choose_semantic_caption_template(
            template_key, sources=source_list
        )
    frame_index, body_index, wrapper_index, closing_index = _decode_template_id(
        template_id
    )

    if not source_list:
        return SemanticCaptionRender(
            text="This spatial audio scene contains no audible sources.",
            template_id=template_id,
            source_regions=(),
            transcript_regions=(),
        )

    frame_prefix, frame_suffix = _SCENE_FRAMES[frame_index]
    body_prefix, middle_separator, final_separator = _BODY_STYLES[body_index]
    wrapper = _SOURCE_WRAPPERS[wrapper_index]
    closing = _CLOSINGS[closing_index]
    phrases = _source_phrases(source_list)

    pieces: list[str] = [frame_prefix, body_prefix]
    source_regions: list[CaptionCharacterRegion] = []
    transcript_regions: list[CaptionCharacterRegion] = []
    cursor = len(frame_prefix) + len(body_prefix)
    for index, phrase in enumerate(phrases):
        if index:
            separator = (
                final_separator if index == len(phrases) - 1 else middle_separator
            )
            pieces.append(separator)
            cursor += len(separator)
        source_text = wrapper.format(
            content=phrase.text,
            source_id=phrase.source_id,
        )
        content_offset = source_text.index(phrase.text)
        rendered_start = cursor
        rendered_end = rendered_start + len(source_text)
        source_start = rendered_start + content_offset
        source_end = source_start + len(phrase.text)
        pieces.append(source_text)
        source_regions.append(
            CaptionCharacterRegion(
                source_id=phrase.source_id,
                source_slot=phrase.source_slot,
                start=source_start,
                end=source_end,
                role="source",
            )
        )
        if phrase.transcript_start is not None and phrase.transcript_end is not None:
            transcript_regions.append(
                CaptionCharacterRegion(
                    source_id=phrase.source_id,
                    source_slot=phrase.source_slot,
                    start=source_start + phrase.transcript_start,
                    end=source_start + phrase.transcript_end,
                    role="transcript",
                )
            )
        cursor = rendered_end

    pieces.extend((frame_suffix, closing))
    text = "".join(pieces)
    for region in (*source_regions, *transcript_regions):
        if not 0 <= region.start < region.end <= len(text):
            raise RuntimeError(f"invalid rendered caption region: {region}")
    return SemanticCaptionRender(
        text=text,
        template_id=template_id,
        source_regions=tuple(source_regions),
        transcript_regions=tuple(transcript_regions),
    )


def validate_semantic_caption_metadata(
    text: str,
    metadata: Mapping[str, Any],
    *,
    expected_source_ids: Sequence[str] | None = None,
) -> None:
    """Fail closed when persisted source spans drift from caption text/state."""

    if metadata.get("version") != SEMANTIC_CAPTION_TEMPLATE_VERSION:
        raise ValueError(
            "unsupported semantic caption template version: "
            f"{metadata.get('version')!r}"
        )
    template_id = metadata.get("template_id")
    _decode_template_id(template_id)
    if int(metadata.get("template_count", -1)) != SEMANTIC_CAPTION_TEMPLATE_COUNT:
        raise ValueError("semantic caption template-count contract changed")

    source_regions = metadata.get("source_regions")
    transcript_regions = metadata.get("transcript_regions")
    if not isinstance(source_regions, list) or not isinstance(transcript_regions, list):
        raise ValueError("semantic caption regions must be lists")

    seen: set[str] = set()
    seen_slots: set[int] = set()
    previous_end = -1
    normalized_sources: dict[str, tuple[int, int]] = {}
    for expected_index, region in enumerate(source_regions):
        if not isinstance(region, Mapping) or region.get("role") != "source":
            raise ValueError("invalid semantic source region")
        source_id = str(region.get("source_id") or "")
        source_slot = int(region.get("source_slot", -1))
        start, end = int(region.get("start", -1)), int(region.get("end", -1))
        if not source_id or source_id in seen or source_slot in seen_slots:
            raise ValueError(f"invalid/duplicate semantic source region: {source_id!r}")
        expected_slot = expected_index
        if source_id.startswith("source_") and source_id[7:].isdigit():
            expected_slot = int(source_id[7:])
        elif source_id.startswith("s") and source_id[1:].isdigit():
            expected_slot = int(source_id[1:])
        if source_slot != expected_slot:
            raise ValueError(
                "semantic source region slot does not match its persistent source ID"
            )
        if start <= previous_end or not 0 <= start < end <= len(text):
            raise ValueError(f"invalid/overlapping semantic source span: {start}:{end}")
        if not text[start:end].strip():
            raise ValueError("semantic source region is empty")
        seen.add(source_id)
        seen_slots.add(source_slot)
        previous_end = end
        normalized_sources[source_id] = (start, end)

    if expected_source_ids is not None:
        expected = [str(value) for value in expected_source_ids]
        actual = [str(region["source_id"]) for region in source_regions]
        if actual != expected:
            raise ValueError(
                "semantic caption source IDs do not match ScenePlan slots: "
                f"caption={actual}, plan={expected}"
            )

    transcript_sources: set[str] = set()
    for region in transcript_regions:
        if not isinstance(region, Mapping) or region.get("role") != "transcript":
            raise ValueError("invalid semantic transcript region")
        source_id = str(region.get("source_id") or "")
        if source_id in transcript_sources or source_id not in normalized_sources:
            raise ValueError(
                f"invalid/duplicate transcript source region: {source_id!r}"
            )
        start, end = int(region.get("start", -1)), int(region.get("end", -1))
        source_start, source_end = normalized_sources[source_id]
        source_slot = int(region.get("source_slot", -1))
        source_region = next(
            item for item in source_regions if str(item.get("source_id")) == source_id
        )
        if source_slot != int(source_region.get("source_slot", -2)):
            raise ValueError("transcript/source persistent slots do not match")
        if not source_start <= start < end <= source_end:
            raise ValueError("transcript region must be nested in its source region")
        if not text[start:end].strip():
            raise ValueError("semantic transcript region is empty")
        transcript_sources.add(source_id)


__all__ = [
    "CaptionCharacterRegion",
    "SEMANTIC_CAPTION_TEMPLATE_COUNT",
    "SEMANTIC_CAPTION_TEMPLATE_VERSION",
    "SemanticCaptionRender",
    "choose_semantic_caption_template",
    "render_semantic_caption",
    "validate_semantic_caption_metadata",
]
